### ISSUE TITLE
List dependencies which violate local engines.node support

### ISSUE THREAD

**Issue by coreyfarrell** [ljharb/ls-engines#15]
This is a nice tool, one feature that would be really nice is a way to have it assume that the local `package.json#engines.node` is correct.  If my package.json supports `{"node": ">=8"}` and `semver@7.1.0` is installed, instead of being told to bump my local version requirement I want to know that semver 7.1.0 is an inappropriate dependency.

**Comment by ljharb** [comment]
Ah, interesting - seems like perhaps the user should be given two choices: a renamed `--save` - ie, an option that's clearly a breaking change, to allow fewer versions; and another that's "package X@Y declares Z" and then perhaps "package X@B is the latest version that meets your engine requirements"?

**Comment by coreyfarrell** [comment]
For my needs simply knowing a list of dependencies that offend my own `engines.node` declaration would be all I need, so for example:
```
package semver@7.1.0 requires node.js >=10
```

Generally my goal would be to catch offensive deep dependencies.  If it's not too much effort to know the latest acceptable version that wouldn't be terrible though I guess it depends on how much processing time the look-ups would take to determine that.  It would require deciding how to handle when older versions of the package did not declare `engines.node`.

**Comment by ljharb** [comment]
This is partially resolved by merely listing the package name; I'm happy to review PRs improving the logic and message, but it's very tricky to make it more helpful than that.
