### ISSUE TITLE
Silence output on success

### ISSUE THREAD

**Issue by tregusti** [ljharb/ls-engines#24]
This is a nice little tool you have here, but having this added to prepare script in many of our projects it would be nice to silence the output when the check is successful.

A good rule for CLI tools is to follow the [UNIX philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) regarding output.

I would prefer a breaking change and silence by default (as per the link above) and add a `--verbose` or `--level` flag. As an alternative solution a `--silent` flag could work, but then the question arises – what to silence. Only success output? All tips? Not errors should be silenced though.

Thoughts?

**Comment by ljharb** [comment]
You can easily silence non-error output with `> /dev/null`.

**Comment by tregusti** [comment]
Thank you, but that is not platform independent. We have many developers on multiple platforms.

The specific problem I have is solvable, but the issue is more that there is unneeded output when there as per practice should be none.

**Comment by ljharb** [comment]
Let's not dance around with euphemisms; it's node, and the only platform where that doesn't work is Windows, so that must be what you're discussing? Why would an argument about the UNIX philosophy apply to Windows?

**Comment by ljharb** [comment]
Looks like Windows has its own way of doing this, so there's no need for individual programs to offer it. https://stackoverflow.com/questions/11463544/how-to-suppress-windows-command-output
